### PR TITLE
Introduce “basic” colour theme

### PR DESCRIPTION
**Pull request by jotaen**
Resolves https://github.com/jotaen/klog/issues/325.

This PR introduces a new `basic` colour theme, which is based on 8-bit ANSI colours. It doesn’t override the default text colour, so the colour of black/white text is “responsive” automatically.

### CODE REVIEW

**Comment by jotaen** [comment]
@vladdeSV if you like, feel free to check out this PR and the new `basic` colour theme.

**Comment by vladdeSV** [comment]
I'll give it a go tomorrow! (busy irl rn)

**Comment by vladdeSV** [comment]
(lol i managed to compile klog on a vps from my phone while in the passenger seat of a car)

Initial impressions are great! Easily readable in both light and dark themes :) 

image

image

image

image

image

image

Of course, with mismanaged themes it did become a bit hard to read

image

image

**Comment by vladdeSV** [comment]
Honestly, looks good to me 🙌

I couldn't figure out how to set 8-bit mode, so didn't test that.

---

Although unrelated to the PR, is it praxis to use British spelling? Mistyped it as "color_scheme", and this is the first time I've noticed to use British

**Comment by jotaen** [comment]
Haha, that’s what I call commitment! 😆 (Glad you didn’t drive, though.) Thanks for checking! It also seems to look good on my end.

> I couldn't figure out how to set 8-bit mode, so didn't test that.

The `basic` theme uses an 8-bit colour palette under the hood (for the [8 basic ANSI colours](https://talyian.github.io/ansicolors/), in contrast to the extended 256 bit colour map). This is only an unimportant implementation detail, though.

> Although unrelated to the PR, is it praxis to use British spelling?

I’m personally used to writing British English, and the entire code base uses British spelling.

**Pull request merged**
