### PR TITLE
Spec: Restructuring and more examples

### PR DESCRIPTION
**Pull request by jotaen**
“Non-functional” refactoring of the specification for improved clarity.

## Changes
- Add examples for all concepts (except summaries) and structure every section in the same way:
  - Brief explanation of what it is on a high-level
  - Examples (formatted as markdown blockquote)
  - Detailed instructions
- Remove redundant statement “Each record must contain a date”, since that’s already clear from the record specification.
- Remove statement for entry summaries “there may be multiple spaces”. This is superfluous, because everything after the first space is treated as part of the summary copy, and an entry summary is allowed to contain (and hence start with) any character.
- Remove term “immediately” (e.g. `MUST be immediately followed by the character`) – that sounds a bit dramatic and doesn’t add any meaning.
- Rewrite section for dates
- Move statements about shifting to section “Time”, because shifting is actually a concept of the time value itself, and not of a range as a whole.
  - Reduce number of examples for shifted ranges, I think the rules should be clear without a complete enumeration.
- Specify value ranges for the hour and minute parts, and distinguish between the rules for 24- and 12-hour clock.
- Explain the general purpose of backticks in the document’s preface.

### CODE REVIEW

**Comment by jotaen** [comment]
@vladdeSV happy to hear your feedback, should you have time to look over this.

**Comment by vladdeSV** [comment]
Sorry, been super busy!

Will take a look at this this weekend 😋

**Comment by jotaen** [comment]
No worries, there is no rush with any of this.

Enjoy your Christmas break also 🎄🎁

**Review by vladdeSV — APPROVED** [review]
Looks good!

**Comment by vladdeSV** [comment]
I think these changes are well written, and I do not see anything that could be improved upon.

The specification seems cleaner now 👍

**Comment by jotaen** [comment]
Thanks for proof-reading this, @vladdeSV!

**Pull request merged**
